"""followers

Revision ID: 705d50eed8b3
Revises: 8ea8b813c927
Create Date: 2020-03-29 13:47:11.397618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705d50eed8b3'
down_revision = '8ea8b813c927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
